[phases.setup]
nixPkgs = ["python313", "ffmpeg-full"]
aptPkgs = ["ffmpeg"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install setuptools",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
